version: '3.9'


volumes:
    prometheus_data: {}
    grafana_data: {}

services:
  nodeexporter:
    image: docker.io/prom/node-exporter:v1.7.0
    container_name: nodeexporter
    network_mode: host
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: always
    labels:
      org.label-schema.group: "monitoring"
