global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'docker-host-alpha'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'incept-node'
    scrape_interval: 5s
    static_configs:
      - targets: ['100.100.218.115:9100']
        labels:
          hostname: incept

  - job_name: 'netcup-node'
    scrape_interval: 5s
    static_configs:
      - targets: ['100.102.90.15:9100']
        labels:
          hostname: netcup
  
  - job_name: 'arm-node'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9100']
        labels:
          hostname: arm

  - job_name: 'pi-node'
    scrape_interval: 5s
    static_configs:
      - targets: ['100.76.32.117:9100']
        labels:
          hostname: pi
  
  - job_name: 'tenet-node'
    scrape_interval: 5s
    static_configs:
      - targets: ['100.122.109.47:9100']
        labels:
          hostname: tenet   

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']


#  - job_name: 'nginx'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['nginxexporter:9113']

#  - job_name: 'aspnetcore'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['eventlog-proxy:5000', 'eventlog:5000']
